services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www

  webserver:
    image: nginx:1.19-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  dbdump:
  mysql_data:
